# Generated by Django 4.1 on 2022-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_user_profile_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
