# Generated by Django 4.1 on 2022-11-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='test_data',
            new_name='address',
        ),
    ]
